#!/bin/bash

GITUSER="Slookeur"
GITEMAIL="sebastien.leroux@ipcms.unistra.fr"

function main_only {
  cd atomes-main

  # To init a git repository:
  #git init

  # To add/create a branch:
  #git branch -M main

  # To link it to a github repo:
  git remote add origin git@github.com:$GITUSER/atomes-doc

  git config user.name $GITUSER
  git config user.email $GITEMAIL
  git config pull.rebase false
  git fetch || printf "fetch did not work\n"
  # Basculement sur la branche "main"
  git checkout -b main || git checkout main
  git add .
  now=`date`
  git commit -m "atomes documentation sources: $now"
  git push origin main
  cd ..
}

function main {
  cd atomes-main
  cp -r ../atomes-jekyll/* .
  cp -r ../prep-jekyll .
  rm -rf _site
  sed 's/\/atomes-doc\///g' index.md > README.md
  nli=`cat README.md|wc -l`
  let nlign=$nli
  let nlign=$nlign-6
  cat README.md|tail --lines=$nlign > index.md
  cp index.md README.md

  # To init a git repository:
  #git init

  # To add/create a branch:
  #git branch -M main

  # To link it to a github repo: 
  git remote add origin git@github.com:$GITUSER/atomes-doc

  git config user.name $GITUSER
  git config user.email $GITEMAIL
  git config pull.rebase false
  git fetch || printf "fetch did not work\n"
  # Basculement sur la branche "main"
  git checkout -b main || git checkout main
  git add .
  now=`date`
  git commit -m "atomes doc sources: $now"
  git push origin main
  cd ..
}

function build {
  cd atomes-jekyll
  rm -rf _site
  #bundle exec jekyll serve
  bundle exec jekyll build
  cd ..
}

function deploy {
  cd atomes-doc
  rm -rf *
  cp -r ../atomes-jekyll/_site/* .
# To init a git repository:
#git init

# To add/create a branch:
#git branch -M main

# To link it to a github repo: 
  git remote add origin git@github.com:$GITUSER/atomes-doc

  git config user.name $GITUSER
  git config user.email $GITEMAIL
  git config pull.rebase false
  git fetch || printf "fetch did not work\n"
  # Basculement sur la branche "gh-pages"
  git checkout -b gh-pages || git checkout gh-pages
  git add .
  now=`date`
  git commit -m "atomes doc website build: $now"
  git push origin gh-pages
  cd ..
}

case "$1" in

  "main_only" )
    main_only
    ;;
  "main" )
    main
    ;;

  "build" )
    build
    ;;

  "deploy" )
    deploy
    ;;

  "main_build" )
    main
    build
    ;;

  "main_deploy" )
    main
    deploy
    ;;

  "main_build_deploy" )
    main
    build
    deploy
    ;;

esac
